# Generated by Django 5.0.14 on 2025-05-08 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_department_remove_userprofile_department_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="nom")),
                ("prenom", models.CharField(max_length=100, verbose_name="prénom")),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="téléphone"
                    ),
                ),
                ("sujet", models.CharField(max_length=200, verbose_name="sujet")),
                ("message", models.TextField(verbose_name="message")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("non_lu", "Non lu"),
                            ("en_cours", "En cours de traitement"),
                            ("traite", "Traité"),
                            ("archive", "Archivé"),
                        ],
                        default="non_lu",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de modification"
                    ),
                ),
                (
                    "departement_destinataire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages_recus",
                        to="accounts.department",
                        verbose_name="département destinataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "message de contact",
                "verbose_name_plural": "messages de contact",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="ContactReponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reponse", models.TextField(verbose_name="réponse")),
                (
                    "date_reponse",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de réponse"
                    ),
                ),
                (
                    "message_original",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="contacts.contactmessage",
                        verbose_name="message original",
                    ),
                ),
                (
                    "repondant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reponses_contact",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="répondant",
                    ),
                ),
            ],
            options={
                "verbose_name": "réponse à un contact",
                "verbose_name_plural": "réponses aux contacts",
                "ordering": ["-date_reponse"],
            },
        ),
    ]
