# Generated by Django 5.2 on 2025-05-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Realisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projet", models.CharField(max_length=255)),
                ("entreprise", models.CharField(max_length=255)),
                ("avis", models.TextField()),
                ("type_personne", models.CharField(max_length=100)),
            ],
        ),
    ]
