# Generated by Django 5.2 on 2025-05-04 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inscription", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscription",
            name="commentaire",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="adresse",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="date_naissance",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="telephone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="inscription",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("confirmee", "Confirmée"),
                    ("refusee", "Refusée"),
                ],
                default="en_attente",
                max_length=50,
            ),
        ),
    ]
