# Generated by Django 5.2 on 2025-05-04 11:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inscription", "0002_inscription_commentaire_utilisateur_adresse_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inscription",
            old_name="formation",
            new_name="formation_nom",
        ),
        migrations.RemoveField(
            model_name="inscription",
            name="commentaire",
        ),
        migrations.RemoveField(
            model_name="inscription",
            name="statut",
        ),
        migrations.RemoveField(
            model_name="utilisateur",
            name="formation_recherchee",
        ),
        migrations.AddField(
            model_name="inscription",
            name="formation_id",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="RechercheFormation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("terme_recherche", models.CharField(max_length=255)),
                ("date_recherche", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inscription.utilisateur",
                    ),
                ),
            ],
        ),
    ]
