# Generated by Django 5.0.14 on 2025-05-08 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StageOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "department",
                    models.CharField(max_length=100, verbose_name="Département"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("missions", models.TextField(verbose_name="Missions")),
                (
                    "required_skills",
                    models.TextField(verbose_name="Compétences requises"),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("duration", models.CharField(max_length=50, verbose_name="Durée")),
                (
                    "stage_type",
                    models.CharField(
                        choices=[
                            ("initiation", "Stage d'initiation"),
                            ("perfectionnement", "Stage de perfectionnement"),
                            ("professionnalisation", "Stage de professionnalisation"),
                            ("fin_etude", "Stage de fin d'études"),
                        ],
                        default="initiation",
                        max_length=50,
                        verbose_name="Type de stage",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("published", "Publié"),
                            ("closed", "Clôturé"),
                            ("archived", "Archivé"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_offers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offre de stage",
                "verbose_name_plural": "Offres de stage",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StageApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=20, verbose_name="Téléphone")),
                ("cv", models.FileField(upload_to="cvs/", verbose_name="CV")),
                (
                    "motivation_letter",
                    models.FileField(
                        upload_to="motivation_letters/",
                        verbose_name="Lettre de motivation",
                    ),
                ),
                (
                    "tracking_code",
                    models.CharField(
                        editable=False,
                        max_length=12,
                        unique=True,
                        verbose_name="Code de suivi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("accepted", "Acceptée"),
                            ("rejected", "Refusée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Candidature déposée le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "stage_offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="stages.stageoffer",
                        verbose_name="Offre de stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidature de stage",
                "verbose_name_plural": "Candidatures de stage",
                "ordering": ["-created_at"],
            },
        ),
    ]
