# Generated by Django 5.0.14 on 2025-05-08 11:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stages", "0002_stageoffer_stageapplication"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="demandestage",
            name="domaine",
        ),
        migrations.RemoveField(
            model_name="demandestage",
            name="utilisateur",
        ),
        migrations.DeleteModel(
            name="DomaineStage",
        ),
        migrations.DeleteModel(
            name="DemandeStage",
        ),
    ]
