# Generated by Django 5.0.14 on 2025-05-08 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_department_remove_userprofile_department_and_more"),
        ("stages", "0003_remove_demandestage_domaine_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stageoffer",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stage_offers",
                to="accounts.department",
                verbose_name="Département",
            ),
        ),
    ]
